version: '3.8'
services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      JUPYTER_TOKEN: '${ACCESS_TOKEN}'
      GRANT_SUDO: 'yes'
    user: 'root'
    volumes:
      - '/hetzhub/apps/jupyterlab/data:/home/jovyan'
    restart: always
    ports:
      - 127.0.0.1:8888:8888
    networks:
      - nginxnetwork
  nginx:
    image: nginx
    container_name: nginx_container
    ports:
      - 443:443           # HTTPS
      - 127.0.0.1:80:80   # HTTP
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf
      - ${NGINX_CERT_PATH}:/etc/nginx/cert.pem
      - ${NGINX_KEY_PATH}:/etc/nginx/key.pem
    restart: always
    networks:
      - nginxnetwork

networks:
  nginxnetwork: